{
 "title": "Epoch Porducer and Convertor",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Produced epoch Message by Partition",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(produced_message_total{container=\"epoch-producer\"}[1m])) by (partition)",
     "legendFormat": "{{ partition }}"
    }
   ]
  },
  {
   "title": "Output RFC3339 Message by Partition",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(produced_message_total{container=\"epoch-convertor\"}[1m])) by (partition)",
     "legendFormat": "{{ partition }}"
    }
   ]
  },
  {
   "title": "Convert Message",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(convert_message_total{}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}